changelog:
  exclude:
    labels:
      - invalid
      - docs
  categories:
    - title: Breaking Changes 💥
      labels:
        - breaking-change
    - title: New Features ✨
      labels:
        - feature
    - title: Layout Changes 💄
      labels:
        - layout
    - title: Bug Fixes 🐛
      labels:
        - bug
    - title: Other Changes
      labels:
        - "*"
